database:
  postgres:
    dbname: postgres
    user: postgres
    password: postgres
    host: localhost
    port: 5432

facebook:
  update_interval: 5  # minutes
  initial_mock_data_size: 50
  new_data_range:
    min: 5
    max: 10 