database:
  host: localhost
  port: 5432
  name: sentiment_db
  user: ${DB_USER}
  password: ${DB_PASSWORD}

facebook:
  access_token: ${FB_ACCESS_TOKEN}
  page_ids: []

slack:
  webhook_url: ${SLACK_WEBHOOK_URL}

email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender_email: ${EMAIL_SENDER}
  sender_password: ${EMAIL_PASSWORD}

model:
  name: "distilbert-base-uncased-finetuned-sst-2-english"
  threshold: 0.5 